/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fbatista.gradle.multiproject;

public class App {
    public String getGreeting() {
        return MessageService.generateMessage();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
