services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - node
    volumes:
      - ./nginx-html:/usr/share/nginx/html
    networks:
      - frontend

  mongo:
    image: mongo:latest
    env_file:
      - ./node-network/.env
    volumes:
      - ./mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"] #comando que irá dizer se está healthy ou não
      interval: 5s #intervalo entre cada comando
      retries: 5 #quantidade de comandos
      start_period: 2s #tempo entre inicialização dos containers e a primeira tentativa do comando
      timeout: 5s #tempo máxima de aguardo para resposta do comando
    networks:
      - db

  node:
    build:
      context: ./node-network
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./node-network:/app
    networks:
      - backend
      - db

networks:
  db:
  backend:
  frontend:
