services:
  nginx:
    image: nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./nginx-html:/usr/share/nginx/html
  
  mongo:
    image: mongo:latest

  node:
    build:
      context: ./node-network
      dockerfile: Dockerfile
    volumes:
      - ./node-network:/app