version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - payments-gateway

networks:
  payments-gateway:
    external: true