GET http://localhost:3000/orders

###

GET http://localhost:3000/orders/061b81b5-c493-44d5-91d8-867f3e4c7223

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "amount": 120.30,
  "credit_card_name": "Fernando Batista",
  "credit_card_number": "1111"
}

###

PATCH http://localhost:3000/orders/061b81b5-c493-44d5-91d8-867f3e4c7223
Content-Type: application/json

{
  "amount": 300.30,
  "credit_card_name": "Gustavo Batista",
  "credit_card_number": "2222"
}

###

DELETE http://localhost:3000/orders/061b81b5-c493-44d5-91d8-867f3e4c7223

###
GET http://localhost:3000/accounts

###

GET http://localhost:3000/accounts/b7043541-8a68-44a4-a0a8-78b4047ebd2f

###

POST http://localhost:3000/accounts
Content-Type: application/json

{
  "name": "Fernando Batista"
}

###

PATCH http://localhost:3000/accounts/8134dcd7-2057-431e-8cc4-3714fc1a1131
Content-Type: application/json

{
  "name": "Fernando H. S. Batista"
}

###

DELETE http://localhost:3000/accounts/b7043541-8a68-44a4-a0a8-78b4047ebd2f